# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a9786f6e55de42b30ddf1fcae1a70730924bd02a4a434aa58cba7c4784928deef948174c697982b10f3d1198a28605f38e651a90d5204a2cb8bae34e130fb66

test:
  secret_key_base: bfec4079301716941571b71d64fa0aeaed63c725cf06f732aa64a5ba6c754fd9d226d843262ff1bbc4e8eed4b0d2a3633d78e88c1e3a6fd1cd6b278ec30b065a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
